<div class="modal" id="politicaDePrivacidade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss='modal'>&times;</button>
				<h4 class="modal-title">
					Política de Privacidade
				</h4>
				<div class="modal-body">
					<div class="entry">
						<p><strong>Geral</strong>. Textos Grátis dá exterma importância em proteger sua privcidade. Esta Política de Privacidade vem a explicar a maneira pela qual Textos Grátis coleta, usa e divulgação as informações pessoais recebidas por você ao usar o site Textos Grátis e seu conteúdo, informação e serviços.</p>
						<p><strong>Consentimento dos Usuários</strong>. AO ACESSAR ESTE SITE,&nbsp;SITUADO NO URL <a title="Textos Grátis" href="http://www.textosgratis.com.br">HTTP://WWW.TEXTOSGRATIS.COM.BR</a> E/OU EM OUTRO LOCAL FORNECIDO POR TEXTOS GRÁTIS (O “SITE”), VOCÊ ESTÁ&nbsp;EXPRESSANDO, CONFIRMANDO E FORNECENDO SEU CONSENTIMENTO À COLETA DA INFORMAÇÃO, USO DA INFORMAÇÃO, E OUTROS PROCEDIMENTOS DESCRITOS NA POLÍTICA DE PRIVACIDADE ABAIXO. Ao Textos Grátis se reserva&nbsp;o direito de&nbsp;modificar esta política a qualquer momento, sem aviso prévio, ao substituir por uma nova política de privacidade&nbsp;neste mesmo loca.&nbsp;A coleta, o uso e a divulgação de sua informação pessoal por Textos Grátis serão decidios pela versão desta política&nbsp;no ato. Por favor verifique esta página de tempo em tempo. Entre em contato por favor se tiver quaisquer perguntas sobre nossa política de privacidade. Coleta e uso da informação. Para que se possa acessar certas áreas ou páginas (como cadastro do autor,&nbsp;enviar a um amigo, etc.) e se cadastrar como usuário do site, este site requere algumas informações pessoais, tais como seu nome, número de telefone e e-mail.&nbsp;Estas informações são usadas por nós para&nbsp;que possamos&nbsp;lhe contactar no evento de mandar&nbsp;novas informações sobre nossa emprsa e serviços, ou para uso comercial e/ou uso interno&nbsp;tal como pesquisa de mercado para melhor entender&nbsp;os dados demográficos dos visitantes do nosso site e de clientes potenciais.&nbsp;Possamos vir a compartilhar esta informação com parcerias autorizadas ou a terceiros que atuam em nosso nome,&nbsp;porém de nenhuma outra forma daremos ou venderemos&nbsp;qualquer informação coletada no site para compradores externos.</p>
						<p><strong>Rastreamento do&nbsp;Usuário</strong>. Este site tem um sistem de rastreamento, onde as atividades de cada usuário único são monitoradas. Isto acontece mesmo sem o usuário estar cadastrado no site, porém enquanto o usuário não preencher dados de cadastro ou se inscrever para receber newsletter, seus dados permaneceram anônimos e não teremos como saber sua identidade. Caso o usuário se cadastrar no site, usaremos os dados de rastreamento para identificar atividades passadas e futuras no site, incluindo as atividades anteriores ao cadastro. Isto inclui as páginas que foram visualizadas. O rastreamento do usuário também nos permite saber como o usuário chegou ao site (se através de sites de busca ou links). O motivo pelo qual usamos o rastreamento de usuário é de analisar as ações dos usuários para poder então melhorar a navegação no site, assim como para entender melhor as prioridades e interesses de nossos clientes potenciais e parcerias, para melhor responder às suas necessidades e aumentar a eficiência dos nossos processos de vendas e marketing.</p>
						<p><strong>Uso de Cookies</strong>. “Cookie” é&nbsp;um pequeno artigo de texto transferido de um site ao computador que está visualizando o site. Mesmo se você não se cadastra no site, ao visitar o site pela primeira vez (ou nas próximas visitas, caso apague seus “cookies”), o cookie é salvo no seu computador,&nbsp;o que permite que você seja automaticamente reconhecido pelo site. Isto é feito por motivos técnicos, entre outros para ativar o “rastreamento do usuário” acima descrito. Além do mais, para a sua conveniência, o “cookie” permite preenchimento automático de formulários no site. poupando lhe o trabalho de inserir a mesma informação nos formulários de cadastro em áreas que exigem estas informações. Não obstante, os prórprios “cookies” não podem ser usados para descobrir a identidade do usuário. A única informação pessoal que temos é a que o usuário nos inofrma. Se preferir não receber ‘cookies”, modifique a configuração do seu browser para recusar “cookies”. Além do mais, você pode apagar os cookies que já estão no seu comptuador.</p>
						<p><strong>Endereços Do Internet Protocol</strong>. Nós coletamos os endereços do IP de todos os visitantes a nosso local. Nós usamos seu IP address a fim administrar o local, ajudamo-lo diagnosticar problemas com nosso usuário, para recolher a informação demográfica larga, e para do “seguir usuário” descrito acima.</p>
						<p><strong>Hyperlinks</strong>. Este local contem hyperlinks a outros locais da correia fotorreceptora. Esta política de privacidade aplica-se somente a este local e não a todos os outros locais, inclusive os locais alcançados pelo hyperlink deste local. Textos Grátis não tem nenhuma responsabilidade, responsabilidade para, ou controle sobre aqueles outros locais da correia fotorreceptora ou recursos de Internet ou seus coleção, uso e divulgação de sua informação pessoal, nem tem-na todo o controle sobre, as políticas de privacidade de alguns destes locais. Quando você sai de nosso local, incluindo ligando do local a um outro local, você deve ler a política de privacidade, se existirem, desde que por tal local.</p>
						<p>A lei aplicável e o jurisdição exclusivo para estabelecir todas as disputas em relação ao uso do local serão as leis e o jurisdição do estado de Israel de acordo com as provisões então da política de fato.</p>
						<p>Textos Grátis acumulará e processar sua informação pessoal nos EUA, Israel ou, do tempo ao tempo, em outras posições nele é descrição a fim fornecê-lo com o serviço competente e eficaz.</p>
						<p>A fim ajudar em proteger a confidencialidade de sua informação pessoal, Textos Grátis aplica as proteções da segurança apropriadas à sensibilidade da informação. Entretanto, na luz da natureza de tecnologias do Internet, a segurança e os riscos da privacidade não podem ser eliminados e, conseqüentemente, Textos Grátis não pode garantir que sua informação pessoal não estará divulgada nas maneiras descritas não de outra maneira nesta política.</p>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</div>